import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1780690483239 implements MigrationInterface {
    name = 'InitSchema1780690483239'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "activity_logs" ("log_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "action" character varying(160) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" character varying(80), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cedee7981584c1984f340ba7174" PRIMARY KEY ("log_id"))`);
        await queryRunner.query(`CREATE TABLE "adoptions" ("adoption_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_id" uuid NOT NULL, "adoption_date" date NOT NULL, "adoption_fee" numeric(10,2), CONSTRAINT "UQ_1587a931d204024da729ff39730" UNIQUE ("request_id"), CONSTRAINT "REL_1587a931d204024da729ff3973" UNIQUE ("request_id"), CONSTRAINT "PK_c78ea086089090f0885ac31e7b3" PRIMARY KEY ("adoption_id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("message_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "conversation_id" uuid NOT NULL, "message_text" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6187089f850b8deeca0232cfeba" PRIMARY KEY ("message_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0777b63da90c27d6ed993dc60b" ON "messages" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("conversation_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adopter_id" uuid NOT NULL, "assigned_employee_id" uuid, "status" character varying(40) NOT NULL DEFAULT 'open', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c00ef2d6a90778048c6b8150819" PRIMARY KEY ("conversation_id"))`);
        await queryRunner.query(`CREATE TABLE "adopters" ("adopter_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "address" text, "city" character varying(100), "registration_date" date NOT NULL, CONSTRAINT "UQ_665437b6a6c44bcd7bba3e7a0f0" UNIQUE ("user_id"), CONSTRAINT "REL_665437b6a6c44bcd7bba3e7a0f" UNIQUE ("user_id"), CONSTRAINT "PK_136edb6d5b4ef72fac49686d684" PRIMARY KEY ("adopter_id"))`);
        await queryRunner.query(`CREATE TABLE "medical_entries" ("entry_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "record_id" uuid NOT NULL, "veterinarian_id" uuid NOT NULL, "diagnosis" text NOT NULL, "treatment" text NOT NULL, "vaccination_status" character varying(80) NOT NULL, "medical_date" date NOT NULL, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0484f20080abd5afe6d1a6702e5" PRIMARY KEY ("entry_id"))`);
        await queryRunner.query(`CREATE TABLE "medical_records" ("record_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pet_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_00f48fa86cd43404c7c3f1cf691" UNIQUE ("pet_id"), CONSTRAINT "REL_00f48fa86cd43404c7c3f1cf69" UNIQUE ("pet_id"), CONSTRAINT "PK_9022f23b7a54a91b9693c027511" PRIMARY KEY ("record_id"))`);
        await queryRunner.query(`CREATE TABLE "pet_images" ("image_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pet_id" uuid NOT NULL, "image_url" text NOT NULL, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_63bf137bf9c0d59f873731bcb6e" PRIMARY KEY ("image_id"))`);
        await queryRunner.query(`CREATE TABLE "vaccinations" ("vaccination_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pet_id" uuid NOT NULL, "vaccine_name" character varying(160) NOT NULL, "vaccination_date" date NOT NULL, "next_due_date" date, "veterinarian_id" uuid NOT NULL, CONSTRAINT "PK_9270059392bad40cad99520bb8b" PRIMARY KEY ("vaccination_id"))`);
        await queryRunner.query(`CREATE TABLE "pets" ("pet_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pet_name" character varying(120) NOT NULL, "species" character varying(80) NOT NULL, "breed" character varying(120), "age" integer, "gender" character varying(30), "color" character varying(80), "weight" numeric(8,2), "description" text, "health_status" character varying(80), "adoption_status" character varying(80) NOT NULL DEFAULT 'available', "arrival_date" date, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6944f2a6e74ce4aca8c41e43804" PRIMARY KEY ("pet_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c8db15270efa3a0eb3fe60ab35" ON "pets" ("pet_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6131a6b7890f49746338f361fd" ON "pets" ("adoption_status") `);
        await queryRunner.query(`CREATE TABLE "adoption_requests" ("request_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adopter_id" uuid NOT NULL, "pet_id" uuid NOT NULL, "status" character varying(40) NOT NULL DEFAULT 'pending', "notes" text, "request_date" date NOT NULL, "reviewed_by" uuid, CONSTRAINT "UQ_46e49e2602060189932dd84d326" UNIQUE ("adopter_id", "pet_id"), CONSTRAINT "PK_284aecc9eae8fe79260b12745ab" PRIMARY KEY ("request_id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("employee_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "department_id" uuid NOT NULL, "salary" numeric(12,2), "hire_date" date, "address" text, CONSTRAINT "UQ_2d83c53c3e553a48dadb9722e38" UNIQUE ("user_id"), CONSTRAINT "REL_2d83c53c3e553a48dadb9722e3" UNIQUE ("user_id"), CONSTRAINT "PK_c9a09b8e6588fb4d3c9051c8937" PRIMARY KEY ("employee_id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("department_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_name" character varying(120) NOT NULL, "manager_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_202cd845b076ed15836884084eb" PRIMARY KEY ("department_id"))`);
        await queryRunner.query(`CREATE TABLE "file_uploads" ("file_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "uploaded_by" uuid, "file_name" character varying(255) NOT NULL, "file_url" text NOT NULL, "file_type" character varying(120), "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4db9492e4c52829794a6d6d4173" PRIMARY KEY ("file_id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("notification_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying(160) NOT NULL, "message" text NOT NULL, "type" character varying(80) NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eaedfe19f0f765d26afafa85956" PRIMARY KEY ("notification_id"))`);
        await queryRunner.query(`CREATE TABLE "oauth_accounts" ("oauth_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" character varying(80) NOT NULL, "provider_user_id" character varying(255) NOT NULL, CONSTRAINT "UQ_ea7720e04e3ae1278575c3159cf" UNIQUE ("provider", "provider_user_id"), CONSTRAINT "PK_47a503ec03bd26c7ade4b161a2d" PRIMARY KEY ("oauth_id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("token_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying(255) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_8672d12baa2133a7b633d49e330" PRIMARY KEY ("token_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7c038e5a589b06cbe4320cc88b" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE TABLE "roles" ("role_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_name" character varying(80) NOT NULL, CONSTRAINT "UQ_ac35f51a0f17e3e1fe121126039" UNIQUE ("role_name"), CONSTRAINT "PK_09f4c8130b54f35925588a37b6a" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(80) NOT NULL, "last_name" character varying(80) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "avatar" text, "role_id" uuid NOT NULL, "phone" character varying(30), "status" character varying(40) NOT NULL DEFAULT 'active', "oauth_provider" character varying(80), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("supplier_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_name" character varying(160) NOT NULL, "phone" character varying(30), "email" character varying(255), "address" text, "city" character varying(100), "country" character varying(100), CONSTRAINT "PK_a2692f796d16e0a30040860112a" PRIMARY KEY ("supplier_id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_supplies" ("supplier_supply_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "supply_id" uuid NOT NULL, "supply_price" numeric(10,2), "delivery_time" character varying(80), "minimum_order_quantity" integer NOT NULL DEFAULT '1', CONSTRAINT "UQ_2af59accfb5b92e57131d1d53c5" UNIQUE ("supplier_id", "supply_id"), CONSTRAINT "PK_4353a400d45ba7f6fe53b68d597" PRIMARY KEY ("supplier_supply_id"))`);
        await queryRunner.query(`CREATE TABLE "supplies" ("supply_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supply_name" character varying(160) NOT NULL, "category" character varying(100) NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "unit_price" numeric(10,2) NOT NULL DEFAULT '0', "low_stock_limit" integer NOT NULL DEFAULT '0', "last_updated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5633584fe4d67a2ce6ec5cacf46" PRIMARY KEY ("supply_id"))`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d54f841fa5478e4734590d44036" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adoptions" ADD CONSTRAINT "FK_1587a931d204024da729ff39730" FOREIGN KEY ("request_id") REFERENCES "adoption_requests"("request_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("conversation_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_6c87c0b90a0d97607ff2ad25f4b" FOREIGN KEY ("adopter_id") REFERENCES "adopters"("adopter_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_aae76e11d434884f45173858fd6" FOREIGN KEY ("assigned_employee_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adopters" ADD CONSTRAINT "FK_665437b6a6c44bcd7bba3e7a0f0" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_entries" ADD CONSTRAINT "FK_e396f9188e141b69c0a81d6fef7" FOREIGN KEY ("record_id") REFERENCES "medical_records"("record_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_entries" ADD CONSTRAINT "FK_7174ce2a6cd6561340d746eb623" FOREIGN KEY ("veterinarian_id") REFERENCES "users"("user_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_records" ADD CONSTRAINT "FK_00f48fa86cd43404c7c3f1cf691" FOREIGN KEY ("pet_id") REFERENCES "pets"("pet_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pet_images" ADD CONSTRAINT "FK_046611b2e97890ef9c8649d2e0b" FOREIGN KEY ("pet_id") REFERENCES "pets"("pet_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaccinations" ADD CONSTRAINT "FK_2441ddbfe02a92e11a974aa1f81" FOREIGN KEY ("pet_id") REFERENCES "pets"("pet_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaccinations" ADD CONSTRAINT "FK_50dac81997d62403cf388a5d56a" FOREIGN KEY ("veterinarian_id") REFERENCES "users"("user_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_18532c169fe353fbc5ab2a1887d" FOREIGN KEY ("created_by") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adoption_requests" ADD CONSTRAINT "FK_09878c30ecb8917cc9bddf667e3" FOREIGN KEY ("adopter_id") REFERENCES "adopters"("adopter_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adoption_requests" ADD CONSTRAINT "FK_c3c6e3068067af06c5523d6cb85" FOREIGN KEY ("pet_id") REFERENCES "pets"("pet_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adoption_requests" ADD CONSTRAINT "FK_bcd1a2c2704a79cd4b6686e2658" FOREIGN KEY ("reviewed_by") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("department_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_ef8a4fb89ff96bbe98f1798798c" FOREIGN KEY ("manager_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_uploads" ADD CONSTRAINT "FK_a24ac1061ddcb44a98413a1e6b2" FOREIGN KEY ("uploaded_by") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" ADD CONSTRAINT "FK_22a05e92f51a983475f9281d3b0" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_supplies" ADD CONSTRAINT "FK_dc68adaaf6faf889674f14384a8" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("supplier_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_supplies" ADD CONSTRAINT "FK_f3e29f5de3ca840b31d3c5c995f" FOREIGN KEY ("supply_id") REFERENCES "supplies"("supply_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "supplier_supplies" DROP CONSTRAINT "FK_f3e29f5de3ca840b31d3c5c995f"`);
        await queryRunner.query(`ALTER TABLE "supplier_supplies" DROP CONSTRAINT "FK_dc68adaaf6faf889674f14384a8"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" DROP CONSTRAINT "FK_22a05e92f51a983475f9281d3b0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "file_uploads" DROP CONSTRAINT "FK_a24ac1061ddcb44a98413a1e6b2"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_ef8a4fb89ff96bbe98f1798798c"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38"`);
        await queryRunner.query(`ALTER TABLE "adoption_requests" DROP CONSTRAINT "FK_bcd1a2c2704a79cd4b6686e2658"`);
        await queryRunner.query(`ALTER TABLE "adoption_requests" DROP CONSTRAINT "FK_c3c6e3068067af06c5523d6cb85"`);
        await queryRunner.query(`ALTER TABLE "adoption_requests" DROP CONSTRAINT "FK_09878c30ecb8917cc9bddf667e3"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_18532c169fe353fbc5ab2a1887d"`);
        await queryRunner.query(`ALTER TABLE "vaccinations" DROP CONSTRAINT "FK_50dac81997d62403cf388a5d56a"`);
        await queryRunner.query(`ALTER TABLE "vaccinations" DROP CONSTRAINT "FK_2441ddbfe02a92e11a974aa1f81"`);
        await queryRunner.query(`ALTER TABLE "pet_images" DROP CONSTRAINT "FK_046611b2e97890ef9c8649d2e0b"`);
        await queryRunner.query(`ALTER TABLE "medical_records" DROP CONSTRAINT "FK_00f48fa86cd43404c7c3f1cf691"`);
        await queryRunner.query(`ALTER TABLE "medical_entries" DROP CONSTRAINT "FK_7174ce2a6cd6561340d746eb623"`);
        await queryRunner.query(`ALTER TABLE "medical_entries" DROP CONSTRAINT "FK_e396f9188e141b69c0a81d6fef7"`);
        await queryRunner.query(`ALTER TABLE "adopters" DROP CONSTRAINT "FK_665437b6a6c44bcd7bba3e7a0f0"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_aae76e11d434884f45173858fd6"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_6c87c0b90a0d97607ff2ad25f4b"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "adoptions" DROP CONSTRAINT "FK_1587a931d204024da729ff39730"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d54f841fa5478e4734590d44036"`);
        await queryRunner.query(`DROP TABLE "supplies"`);
        await queryRunner.query(`DROP TABLE "supplier_supplies"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c038e5a589b06cbe4320cc88b"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "oauth_accounts"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "file_uploads"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "adoption_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6131a6b7890f49746338f361fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8db15270efa3a0eb3fe60ab35"`);
        await queryRunner.query(`DROP TABLE "pets"`);
        await queryRunner.query(`DROP TABLE "vaccinations"`);
        await queryRunner.query(`DROP TABLE "pet_images"`);
        await queryRunner.query(`DROP TABLE "medical_records"`);
        await queryRunner.query(`DROP TABLE "medical_entries"`);
        await queryRunner.query(`DROP TABLE "adopters"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0777b63da90c27d6ed993dc60b"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "adoptions"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
    }

}
